In [1]:
import warnings
warnings.filterwarnings('ignore')
import pdb

In [2]:
from selenium import webdriver
import pandas as pd

In [3]:
from selenium.webdriver.common.keys import Keys

In [4]:
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By

In [5]:
from selenium.webdriver.common.action_chains import ActionChains

# TAKE ALL DATA FROM ROWS , DO NOT GO TO FLIGHT DETAILS SECTION

In [98]:
class Yatra():
    """to fetch flight prices from Yatra.com"""
    
    def __init__(self, url = 'https://www.yatra.com/flights'):
        self.url = url
        self.driver = webdriver.Chrome('chromedriver.exe')
        self.driver.maximize_window()
        
    def open_url(self):
        self.driver.get(self.url)
        self.driver.implicitly_wait(5)
        self.driver.find_element_by_xpath("//div[@class='ripple-parent search-height demo-icon icon-go']").click()
        
    def fetch_data(self):
#         carrier_list = []
#         depart_city_list = []
#         arrive_city_list = []
#         depart_time_list = []
#         arrive_time_list = []
#         no_of_stops_list = []
#         duration_list = []
#         price_list = []
#         travel_date_list = []
        
#         temp_carrier = self.driver.find_elements_by_xpath("//div[@class='fs-13 airline-name no-pad col-8']/span")
#         # fetching travel date from top line ==> we are getting only 1 webelement, so 1 value only
#         temp_travel_date = self.driver.find_element_by_xpath("//div[@class='day-li text-center cursor-pointer pr active font-primary-color']/p[@class='fs-12']")
#         temp_depart_city = self.driver.find_elements_by_xpath("//p[@class='fs-10 font-lightgrey no-wrap city ellipsis']")[::2]
#         temp_arrive_city = self.driver.find_elements_by_xpath("//p[@class='fs-10 font-lightgrey no-wrap city ellipsis']")[1::2]
#         temp_depart_time = self.driver.find_elements_by_xpath("//div[@class='fs-15 bold time']")
#         temp_arrive_time = self.driver.find_elements_by_xpath("//p[@class='bold fs-15 mb-2 pr time']")
#         temp_duration = self.driver.find_elements_by_xpath("//p[@class='fs-12 bold du mb-2']")
#         temp_price = self.driver.find_elements_by_xpath("//div[@class='i-b tipsy fare-summary-tooltip fs-18']")
#         temp_no_of_stops = self.driver.find_elements_by_xpath("//div[@class=' font-lightgrey fs-10 tipsy i-b fs-10']/span")
        self.driver.implicitly_wait(3)
        carrier_list = [i.text for i in self.driver.find_elements_by_xpath("//div[@class='fs-13 airline-name no-pad col-8']/span")]
        self.driver.implicitly_wait(3)
        depart_city_list = [i.text for i in self.driver.find_elements_by_xpath("//p[@class='fs-10 font-lightgrey no-wrap city ellipsis']")[::2]]
        self.driver.implicitly_wait(3)
        arrive_city_list = [i.text for i in self.driver.find_elements_by_xpath("//p[@class='fs-10 font-lightgrey no-wrap city ellipsis']")[1::2]]
        self.driver.implicitly_wait(3)
        depart_time_list = [i.text for i in self.driver.find_elements_by_xpath("//div[@class='fs-15 bold time']")]
        self.driver.implicitly_wait(3)
        arrive_time_list = [i.text for i in self.driver.find_elements_by_xpath("//p[@class='bold fs-15 mb-2 pr time']")]
        self.driver.implicitly_wait(3)
        no_of_stops_list = [i.text for i in self.driver.find_elements_by_xpath("//div[@class=' font-lightgrey fs-10 tipsy i-b fs-10']/span")]
        self.driver.implicitly_wait(3)
        duration_list = [i.text for i in self.driver.find_elements_by_xpath("//p[@class='fs-12 bold du mb-2']")]
        self.driver.implicitly_wait(3)
        price_list = [i.text for i in self.driver.find_elements_by_xpath("//div[@class='i-b tipsy fare-summary-tooltip fs-18']")]
        self.driver.implicitly_wait(3)
        travel_date_list = [self.driver.find_element_by_xpath("//div[@class='day-li text-center cursor-pointer pr active font-primary-color']/p[@class='fs-12']").text]*len(price_list)
        self.driver.implicitly_wait(3)
        
        df_9_oct_19 = pd.DataFrame({'Carrier':carrier_list,'Depart':depart_city_list,'Arrive':arrive_city_list,'Travel Date':travel_date_list,'Duration':duration_list,'Dep-Time':depart_time_list,'Arrive-Time':arrive_time_list,'No. of Stops':no_of_stops_list,'Fare':price_list})
        df_9_oct_19.to_csv('flight_prices_9_oct_19.csv',index=False)
        
        #         # get root of journey
#         a = ActionChains(self.driver) # object of actionchains
#         temp_stop_between = self.driver.find_elements_by_xpath("//div[@class='duration-stop clearfix pr bdr-btm-grey']")
#         for i in range(len(temp_stop_between)):
#             pdb.set_trace()
#             try:
#                 no_of_circles = len(temp_stop_between[i].find_elements_by_xpath(".//i[@class='tipsy white-circle']"))
#             except NoSuchElementException:
#                 no_of_circles = 0
#             self.driver.implicitly_wait(3)
#             if no_of_circles == 1:
#                 a.move_to_element(temp_stop_between[i].find_element_by_xpath(".//i[@class='tipsy white-circle']")).perform()
#                 temp_first_stop = temp_stop_between[i].find_element_by_css_selector("css=td.text-left pr-5")
#                 temp_second_stop = 'NA'
#             elif no_of_circles == 2:
#                 temp_first_stop = temp_stop_between[i].find_elements_by_xpath(".//i[@class='tipsy white-circle'][1]/tbody/tr[2]/td[@class='text-left pr-5']")
#                 temp_second_stop = temp_stop_between[i].find_elements_by_xpath(".//i[@class='tipsy white-circle'][2]/tbody/tr[2]/td[@class='text-left pr-5']")
#             elif no_of_circles == 0:
#                 temp_first_stop = 'NA'
#                 temp_second_stop = 'NA'

In [99]:
y = Yatra()
y.open_url()
# call fetch_data method seperately after entering the city names and scrolling down manually.

In [100]:
y.fetch_data()

In [101]:
pd.read_csv('flight_prices_9_oct_19.csv',index_col=None)

,Carrier,Depart,Arrive,Travel Date,Duration,Dep-Time,Arrive-Time,No. of Stops,Fare
0,Air India,New Delhi,Mumbai,"Fri, 29 Oct",2h 05m,07:00,09:05,Non Stop,"4,931"
1,Air India,New Delhi,Mumbai,"Fri, 29 Oct",2h 10m,08:00,10:10,Non Stop,"4,931"
2,Air India,New Delhi,Mumbai,"Fri, 29 Oct",2h 10m,10:40,12:50,Non Stop,"4,931"
3,Air India,New Delhi,Mumbai,"Fri, 29 Oct",2h 15m,09:00,11:15,Non Stop,"4,931"
4,Air India,New Delhi,Mumbai,"Fri, 29 Oct",3h 10m,15:05,18:15,1 Stop,"4,931"
...,...,...,...,...,...,...,...,...,...
131,Go First,New Delhi,Mumbai,"Fri, 29 Oct",7h 30m,08:10,15:40,1 Stop,"12,519"
132,Go First,New Delhi,Mumbai,"Fri, 29 Oct",9h 20m,08:10,17:30,1 Stop,"12,519"
133,IndiGo,New Delhi,Mumbai,"Fri, 29 Oct",9h 10m,07:40,16:50,1 Stop,"12,780"
134,Go First,New Delhi,Mumbai,"Fri, 29 Oct",6h 45m,12:35,19:20,1 Stop,"12,939"
135,Air India,New Delhi,Mumbai,"Fri, 29 Oct",12h 45m,07:00,19:45,1 Stop,"13,291"

### Below code not able to open each flight detail's subsection.

In [ ]:
class Yatra():
    """to fetch flight prices from Yatra.com"""
    
    def __init__(self, url = 'https://www.yatra.com/flights'):
        self.url = url
        self.driver = webdriver.Chrome('chromedriver.exe')
        self.driver.maximize_window()
        
    def open_url(self):
        self.driver.get(self.url)
        self.driver.implicitly_wait(5)
        self.driver.find_element_by_xpath("//div[@class='ripple-parent search-height demo-icon icon-go']").click()
        
    def click_sections(self):
        disp_section_wbes = self.driver.find_elements_by_xpath("//span[@class='ml-2 fs-6 v-aligm-m rotate-anim ytfi-angle-down i-b ']")
        for i in range(len(disp_section_wbes)):
# #             pdb.set_trace()
#             wait = WebDriverWait(self.driver,10)
#             element = wait.until(EC.element_to_be_clickable((By.XPATH,"//span[@class='ml-2 fs-6 v-aligm-m rotate-anim ytfi-angle-down i-b ']")))
            self.driver.implicitly_wait(5)
            disp_section_wbes[i].click()
            self.driver.implicitly_wait(5)
    def fetch_data(self):
        try:
    #       get webelements for all main sections after slide down
            details_wbes = self.driver.find_elements_by_xpath("//div[@class='flight-details pr slide-down ovf-hidden full-width table']")
            # loop each section seperately to fetch details
            carrier_list = []
            depart_city_list = []
            first_stop_list = []
            arrive_city_list = []
            depart_time_list = []
            arrive_time_list = []
            travel_date_list = []
            no_of_stops_list = []
            for i in details_wbes :
                self.driver.implicitly_wait(5)
                # get number of subsections to decide how many routes are there
                no_of_subsections = len(i.find_elements_by_xpath(".//div[@class='schedule']"))
                if no_of_subsections == 1: # condition for non-stop flight details
                    temp_carrier = i.find_element_by_xpath(".//div[@class='airline-text full-width mb-2']/span").text
                    self.driver.implicitly_wait(2)
                    temp_depart_city = i.find_element_by_xpath(".//div[@class='pr-18 depart-det city pull-left text-left']/div[@class='mb-2 fs-13 no-wrap ellipsis']").text
                    self.driver.implicitly_wait(2)
    #                 temp_first_stop = i.find_element_by_xpath(".//div[@class='arrive-det city pull-left text-left'][1]/div[@class='mb-2 fs-13 no-wrap ellipsis']").text
                    temp_arrive_city = i.find_element_by_xpath(".//div[@class='arrive-det city pull-left text-left']/div[@class='mb-2 fs-13 no-wrap ellipsis']").text
                    self.driver.implicitly_wait(2)
                    temp_depart_time = i.find_element_by_xpath(".//div[@class='pr-18 depart-det city pull-left text-left']/div[@class='bold fs-16 mb-2']").text
                    self.driver.implicitly_wait(2)
                    temp_arrive_time = i.find_element_by_xpath(".//div[@class='arrive-det city pull-left text-left']/div[@class='bold fs-16 mb-2']").text
                    self.driver.implicitly_wait(2)
                    temp_travel_date = i.find_element_by_xpath(".//div[@class='pr-18 depart-det city pull-left text-left']/div[@class='bold fs-12 mb-5']").text
                    self.driver.implicitly_wait(2)
                    temp_no_of_stops = 1
                    self.driver.implicitly_wait(2)
                    temp_price = i.find_element_by_xpath(".//div[@class='v-aligm-t']/div[@class='fare-summary-rules']").find_element_by_xpath(".//tfoot/i[@class='fs-15 ytfi-rupee']").text

                    #store
                    self.driver.implicitly_wait(2)
                    carrier_list.append(temp_carrier)
                    depart_city_list.append(temp_depart_city)
                    first_stop_list.append('NA')
                    arrive_city_list.append(temp_arrive_city)
                    depart_time_list.append(temp_depart_time)
                    arrive_time_list.append(temp_arrive_time)
                    travel_date_list.append(temp_travel_date)
                    no_of_stops_list.append(temp_no_of_stops)
                    price_list = temp_price
                    
                elif no_of_subsections == 2: # condition for 1-stop flight details
                    self.driver.implicitly_wait(2)
                    temp_carrier = i.find_element_by_xpath(".//div[@class='airline-text full-width mb-2']/span").text
                    self.driver.implicitly_wait(2)
                    temp_depart_city = i.find_element_by_xpath(".//div[@class='pr-18 depart-det city pull-left text-left'][1]/div[@class='mb-2 fs-13 no-wrap ellipsis']").text
                    self.driver.implicitly_wait(2)
                    temp_first_stop = i.find_element_by_xpath(".//div[@class='arrive-det city pull-left text-left'][1]/div[@class='mb-2 fs-13 no-wrap ellipsis']").text
                    self.driver.implicitly_wait(2)
                    temp_arrive_city = i.find_element_by_xpath(".//div[@class='arrive-det city pull-left text-left'][2]/div[@class='mb-2 fs-13 no-wrap ellipsis']").text
                    self.driver.implicitly_wait(2)
                    temp_depart_time = i.find_element_by_xpath(".//div[@class='pr-18 depart-det city pull-left text-left'][1]/div[@class='bold fs-16 mb-2']").text
                    self.driver.implicitly_wait(2)
                    temp_arrive_time = i.find_element_by_xpath(".//div[@class='arrive-det city pull-left text-left'][2]/div[@class='bold fs-16 mb-2']").text
                    self.driver.implicitly_wait(2)
                    temp_travel_date = i.find_element_by_xpath(".//div[@class='pr-18 depart-det city pull-left text-left'][1]/div[@class='bold fs-12 mb-5']").text
                    self.driver.implicitly_wait(2)
                    temp_no_of_stops = 2
                    self.driver.implicitly_wait(2)
                    temp_price = i.find_element_by_xpath(".//div[@class='v-aligm-t']/div[@class='fare-summary-rules']").find_element_by_xpath(".//tfoot/i[@class='fs-15 ytfi-rupee']").text

                    #store
                    self.driver.implicitly_wait(2)
                    carrier_list.append(temp_carrier)
                    depart_city_list.append(temp_depart_city)
                    first_stop_list.append(temp_first_stop)
                    arrive_city_list.append(temp_arrive_city)
                    depart_time_list.append(temp_depart_time)
                    arrive_time_list.append(temp_arrive_time)
                    travel_date_list.append(temp_travel_date)
                    no_of_stops_list.append(temp_no_of_stops)
                    price_list = temp_price

    #             pdb.set_trace()

            df_7_oct_1 = pd.DataFrame({'Carrier':carrier_list,'Depart':depart_city_list,'Arrive':arrive_city_list,'Travel Date':travel_date_list,'Dep-Time':depart_time_list,'Arrive-Time':arrive_time_list,'No. of Stops':no_of_stops_list,'First stop':first_stop_list,'Fare':price_list})
            df_7_oct_1.to_csv('flight_prices_7_oct_1.csv',index=False)
        except:
            df_7_oct_1 = pd.DataFrame({'Carrier':carrier_list,'Depart':depart_city_list,'Arrive':arrive_city_list,'Travel Date':travel_date_list,'Dep-Time':depart_time_list,'Arrive-Time':arrive_time_list,'No. of Stops':no_of_stops_list,'First stop':first_stop_list,'Fare':price_list})
            df_7_oct_1.to_csv('flight_prices_7_oct_1.csv',index=False)

In [ ]:
y = Yatra()
y.open_url()
# call fetch_data method seperately after entering the city names and scrolling down manually.

In [ ]:
# run it only after scrolling down and entering cities manually
y.click_sections()
# also , Before runnning this, click and expand all subsections
# df_7_oct_1 = y.fetch_data()

In [ ]:
df_Del_MUM_6_Oct

In [ ]:
df_Del_MUM_5_Oct.to_csv('fare_yatra_Del_Mum_5_Oct.csv',index=False)

### Merge all .csv files

In [9]:
df_1 = pd.read_csv('flight_prices_9_oct_1.csv',index_col=None)
df_2 = pd.read_csv('flight_prices_9_oct_2.csv',index_col=None)
df_3 = pd.read_csv('flight_prices_9_oct_3.csv',index_col=None)
df_4 = pd.read_csv('flight_prices_9_oct_4.csv',index_col=None)
df_5 = pd.read_csv('flight_prices_9_oct_5.csv',index_col=None)
df_6 = pd.read_csv('flight_prices_9_oct_6.csv',index_col=None)
df_7 = pd.read_csv('flight_prices_9_oct_7.csv',index_col=None)
df_8 = pd.read_csv('flight_prices_9_oct_8.csv',index_col=None)
df_9 = pd.read_csv('flight_prices_9_oct_9.csv',index_col=None)
df_10 = pd.read_csv('flight_prices_9_oct_10.csv',index_col=None)
df_11 = pd.read_csv('flight_prices_9_oct_11.csv',index_col=None)
df_12 = pd.read_csv('flight_prices_9_oct_12.csv',index_col=None)
df_13 = pd.read_csv('flight_prices_9_oct_13.csv',index_col=None)
df_14 = pd.read_csv('flight_prices_9_oct_14.csv',index_col=None)
df_15 = pd.read_csv('flight_prices_9_oct_15.csv',index_col=None)
df_16 = pd.read_csv('flight_prices_9_oct_16.csv',index_col=None)
df_17 = pd.read_csv('flight_prices_9_oct_17.csv',index_col=None)
df_18 = pd.read_csv('flight_prices_9_oct_18.csv',index_col=None)
df_19 = pd.read_csv('flight_prices_9_oct_19.csv',index_col=None)

In [19]:
df_final = pd.concat([df_1,df_2,df_3,df_4,df_5,df_6,df_7,df_8,df_9,df_10,df_11,df_12,df_13,df_14,df_15,df_16,df_17,df_18,df_19],ignore_index=True)

In [20]:
df_final

,Carrier,Depart,Arrive,Travel Date,Duration,Dep-Time,Arrive-Time,No. of Stops,Fare
0,Air Asia,New Delhi,Mumbai,"Sun, 10 Oct",5h 55m,16:15,22:10,1 Stop,"5,953"
1,Air Asia,New Delhi,Mumbai,"Sun, 10 Oct",6h 00m,05:20,11:20,1 Stop,"5,953"
2,Air Asia,New Delhi,Mumbai,"Sun, 10 Oct",6h 35m,09:25,16:00,1 Stop,"5,953"
3,Air Asia,New Delhi,Mumbai,"Sun, 10 Oct",11h 45m,18:35,06:20\n+ 1 day,1 Stop,"5,953"
4,Air Asia,New Delhi,Mumbai,"Sun, 10 Oct",14h 05m,16:15,06:20\n+ 1 day,1 Stop,"5,953"
...,...,...,...,...,...,...,...,...,...
2727,Go First,New Delhi,Mumbai,"Fri, 29 Oct",7h 30m,08:10,15:40,1 Stop,"12,519"
2728,Go First,New Delhi,Mumbai,"Fri, 29 Oct",9h 20m,08:10,17:30,1 Stop,"12,519"
2729,IndiGo,New Delhi,Mumbai,"Fri, 29 Oct",9h 10m,07:40,16:50,1 Stop,"12,780"
2730,Go First,New Delhi,Mumbai,"Fri, 29 Oct",6h 45m,12:35,19:20,1 Stop,"12,939"
2731,Air India,New Delhi,Mumbai,"Fri, 29 Oct",12h 45m,07:00,19:45,1 Stop,"13,291"

In [21]:
df_final.to_csv('flight_prices_final.csv',index=False)

In [22]:
pd.read_csv('flight_prices_final.csv',index_col=None)

,Carrier,Depart,Arrive,Travel Date,Duration,Dep-Time,Arrive-Time,No. of Stops,Fare
0,Air Asia,New Delhi,Mumbai,"Sun, 10 Oct",5h 55m,16:15,22:10,1 Stop,"5,953"
1,Air Asia,New Delhi,Mumbai,"Sun, 10 Oct",6h 00m,05:20,11:20,1 Stop,"5,953"
2,Air Asia,New Delhi,Mumbai,"Sun, 10 Oct",6h 35m,09:25,16:00,1 Stop,"5,953"
3,Air Asia,New Delhi,Mumbai,"Sun, 10 Oct",11h 45m,18:35,06:20\n+ 1 day,1 Stop,"5,953"
4,Air Asia,New Delhi,Mumbai,"Sun, 10 Oct",14h 05m,16:15,06:20\n+ 1 day,1 Stop,"5,953"
...,...,...,...,...,...,...,...,...,...
2727,Go First,New Delhi,Mumbai,"Fri, 29 Oct",7h 30m,08:10,15:40,1 Stop,"12,519"
2728,Go First,New Delhi,Mumbai,"Fri, 29 Oct",9h 20m,08:10,17:30,1 Stop,"12,519"
2729,IndiGo,New Delhi,Mumbai,"Fri, 29 Oct",9h 10m,07:40,16:50,1 Stop,"12,780"
2730,Go First,New Delhi,Mumbai,"Fri, 29 Oct",6h 45m,12:35,19:20,1 Stop,"12,939"
2731,Air India,New Delhi,Mumbai,"Fri, 29 Oct",12h 45m,07:00,19:45,1 Stop,"13,291"